Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : anderson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : igor
// Data atual  : 08/11/2022
Var
vet: vetor[1..10] de inteiro
posicao,numero,soma:inteiro
Inicio
 para posicao:=1 ate 10 faca
 escreval("Digite o ",posicao," número: ")
 leia(numero)
 soma <- soma + numero
 fimpara
escreval(" A soma de todos os números é: ",soma)
Fimalgoritmo
